name: Deploy to EdgeOne Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/deploy.yml'  # 忽略deploy.yml的变更

jobs:
  deploy-edgeone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Prepare deployment directory
        run: |
          mkdir -p ./dist
          cp -r ./api ./dist/
          cp -r ./src ./dist/
          cp ./edgeone.json ./dist/
          cp ./package.json ./dist/
          echo "Deployment directory prepared"
          ls -la ./dist

      - name: Determine project name
        id: proj
        shell: bash
        run: |
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d '/' -f2)
          echo "name=${EDGEONE_PROJECT_NAME:-$REPO_NAME}" >> $GITHUB_OUTPUT
        env:
          EDGEONE_PROJECT_NAME: ${{ secrets.EDGEONE_PROJECT_NAME }}

      - name: Deploy to EdgeOne Pages
        run: |
          echo "=== EdgeOne Deployment Debug Info ==="
          echo "Project name: ${{ steps.proj.outputs.name }}"
          echo "Deployment directory contents:"
          ls -la ./dist
          echo "EdgeOne config file:"
          cat ./dist/edgeone.json
          echo "=== Starting EdgeOne Deployment ==="
          
          # 检查API Token是否存在
          if [ -z "${{ secrets.EDGEONE_API_TOKEN }}" ]; then
            echo "ERROR: EDGEONE_API_TOKEN is not set!"
            exit 1
          fi
          
          # 执行部署
          npx edgeone pages deploy ./dist -n "${{ steps.proj.outputs.name }}" -t "${{ secrets.EDGEONE_API_TOKEN }}" -e production
          
          echo "=== EdgeOne Deployment Completed ==="
        env:
          EDGEONE_API_TOKEN: ${{ secrets.EDGEONE_API_TOKEN }}
