name: Selective Deployment

on:
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      deploy-vercel: ${{ steps.changes.outputs.vercel }}
      deploy-edgeone: ${{ steps.changes.outputs.edgeone }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for changes
        id: changes
        run: |
          # 获取变更的文件列表
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          echo "Changed files: $CHANGED_FILES"
          
          # 检查是否有源代码文件变更（同时部署两个平台）
          if echo "$CHANGED_FILES" | grep -E '(api/|src/|package\.json|vercel\.json|edgeone\.json|README\.md|LICENSE|node-functions/)'; then
            echo "vercel=true" >> $GITHUB_OUTPUT
            echo "edgeone=true" >> $GITHUB_OUTPUT
            echo "Deployment strategy: Both platforms (source files updated)"
          # 检查是否只更新了deploy.yml
          elif echo "$CHANGED_FILES" | grep -q "^\.github/workflows/deploy\.yml$" && ! echo "$CHANGED_FILES" | grep -E '(api/|src/|package\.json|vercel\.json|edgeone\.json|README\.md|LICENSE|node-functions/)'; then
            echo "vercel=true" >> $GITHUB_OUTPUT
            echo "edgeone=false" >> $GITHUB_OUTPUT
            echo "Deployment strategy: Vercel only (deploy.yml updated)"
          # 检查是否只更新了edgeone.yml
          elif echo "$CHANGED_FILES" | grep -q "^\.github/workflows/edgeone\.yml$" && ! echo "$CHANGED_FILES" | grep -E '(api/|src/|package\.json|vercel\.json|edgeone\.json|README\.md|LICENSE|node-functions/)'; then
            echo "vercel=false" >> $GITHUB_OUTPUT
            echo "edgeone=true" >> $GITHUB_OUTPUT
            echo "Deployment strategy: EdgeOne only (edgeone.yml updated)"
          # 检查是否只更新了selective-deploy.yml（不部署）
          elif echo "$CHANGED_FILES" | grep -q "^\.github/workflows/selective-deploy\.yml$" && ! echo "$CHANGED_FILES" | grep -E '(api/|src/|package\.json|vercel\.json|edgeone\.json|README\.md|LICENSE|node-functions/)'; then
            echo "vercel=false" >> $GITHUB_OUTPUT
            echo "edgeone=false" >> $GITHUB_OUTPUT
            echo "Deployment strategy: No deployment (only selective-deploy.yml updated)"
          # 其他情况：不部署
          else
            echo "vercel=false" >> $GITHUB_OUTPUT
            echo "edgeone=false" >> $GITHUB_OUTPUT
            echo "Deployment strategy: No deployment (no relevant changes)"
          fi
          
          echo "Final decision - Vercel: ${{ steps.changes.outputs.vercel }}, EdgeOne: ${{ steps.changes.outputs.edgeone }}"

  deploy-vercel:
    needs: check-changes
    if: needs.check-changes.outputs.deploy-vercel == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_BASE_URL: ${{ secrets.GEMINI_BASE_URL }}
          GEMINI_API_VERSION: ${{ secrets.GEMINI_API_VERSION }}

  deploy-edgeone:
    needs: check-changes
    if: needs.check-changes.outputs.deploy-edgeone == 'true'
    uses: ./.github/workflows/edgeone.yml
    with:
      deploy-edgeone: true
    secrets: inherit
